# Prepend HOME bin to path
path=("$HOME/bin" $path)

# Append installation to path
path+="/usr/local/Cellar/"
path+="$HOME/.npm-packages/bin"
path+="/Applications/Sublime Text.app/Contents/SharedSupport/bin"

# commands that should be available to non-interactive users
alias gh-link="git remote -v | grep fetch | awk '{print \$2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//' | sed 's/\.git/\/tree\/main/'"

