# Prepend some things to the path
path=("$HOME/bin" $path)
path=("/opt/homebrew/bin/vim" $path)

# Append installation to path
path+="/usr/local/Cellar/"
path+="$HOME/.npm-packages/bin"
path+="/Applications/Sublime Text.app/Contents/SharedSupport/bin"
path+="$HOME/.cargo/bin"

# commands that should be available to non-interactive users
alias gh-link="git remote -v | grep fetch | awk '{print \$2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//' | sed 's/\.git/\/tree\/main/'"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
