# main path
export PATH="/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:$HOME/bin:$PATH"

# postgres installation
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"

# ruby installation
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"

# npm installation
export PATH="$HOME/.npm-packages/bin:$PATH"

# sublime installation
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# use node 12 over other versions
export PATH="/usr/local/opt/node@12/bin:$PATH"

# non-interactive commands
alias gh-link="git remote -v | grep fetch | awk '{print \$2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//' | sed 's/\.git/\/tree\/main/'"

