# main path
export PATH="/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:$PATH"

# postgres installation
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"

# ruby installation
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"

# npm installation
export PATH="$HOME/.npm-packages/bin:$PATH"

# emacs mode 
bindkey -e

# set colors
autoload -U colors && colors

# prompts
export PROMPT="
 <%?> [%~] $program %{$fg[default]%}
 %{$fg[magenta]%}[%*] %{$fg[cyan]%}%n@%M %{$fg[default]%}$ "

# ls preferences
alias ls='ls -Fhp'
export CLICOLOR=1
export LSCOLORS='GxFxCxDxBxegedabagaced'

# other aliases
alias python3.6='python3'

