# emacs mode
bindkey -e
export SHELL="$(which zsh)"
export EDITOR="nvim"

# tab stop size
tabs -2

# set colors
autoload -U colors && colors

# prompts
export PROMPT="
 <%?> [%~] $program %{$fg[default]%}
 %{$fg[magenta]%}[%*] %{$fg[cyan]%}%n@%m %{$fg[default]%}$ "
 export LESS="-x4R"

# ls preferences
alias ls='ls -Fhp'
export CLICOLOR=1
export LSCOLORS='GxFxCxDxBxegedabagaced'

# golang dir
export GOPATH="$HOME/bin/go"

# github aliases
alias pr='gh pr create --web'
alias pr-pull='git fetch && git checkout'

# other aliases
alias vi='nvim'
alias vim='nvim'
alias sl='sqlite3'
alias ez='vim ~/.zshrc'

# beep when done!
alias beep="echo -n '\a'"

# edit command in editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-rompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'r:|[._-]=**' 'l:|=* r:|=*'
zstyle :compinstall filename '/Users/apetros/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

source "$HOME/.zshrc.local"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
alias vfi='vim "$(rg . | fzf | cut -d ":" -f 1)"'
